dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
dotenv: .env
dev_deployment_artifacts: True
networks:
  development:
    verify: False
  ganache:
    verify: False
  kovan:
    verify: True
    dai_token: "0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa"
    comp_token: "0x61460874a7196d6a22D1eE4922473664b3E95270"
    bat_token: "0x482dC9bB08111CB875109B075A40881E48aE02Cd"
    usdt_token: "0x07de306FF27a2B630B1141956844eB1552B956B5"
    usdc_token: "0xb7a4F3E9097C08dA09517b5aB877F7a917224ede"
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
